### ISSUE TITLE
Ethernet-over-IPv6 tunnel app

### ISSUE THREAD

**Issue by lukego** [SnabbCo/snabbswitch#100]
Support point-to-point tunnels based on the simple [Keyed IPv6 Tunnels](http://tools.ietf.org/html/draft-mkonstan-keyed-ipv6-tunnel-01) internet draft.

**Comment by theo19** [comment]
Even if this is closed, it might be worth to add that in early 2017, the draft has eveolved to the standard "Keyed IPv6 Tunnel", see https://tools.ietf.org/html/rfc8159
