### ISSUE TITLE
Neutron error & statistics reporting

### ISSUE THREAD

**Issue by lukego** [SnabbCo/snabbswitch#191]
Snabb NFV's agent should be able to report errors/alarms/statistics to OpenStack in a simple way.

**Comment by thisisrmr** [comment]
Is this issue still valid?

**Comment by lukego** [comment]
Here is the current architecture: [Snabb NFV Architecture](https://github.com/SnabbCo/snabb-nfv/wiki/Architecture). Overall we have worked to make the code small and conservative. Small: there is no agent anymore. Conservative: we do all API extensions via `binding:vif_profile` key/value options instead of relying on API extensions like QoS. This makes it easy for us to retarget between OpenStack versions and limits the impact of upstream activity/non-activity (e.g. QoS API not being merged for 2+ years).

Code for Neutron (based on Icehouse):
https://github.com/SnabbCo/neutron/commits/nfv/icehouse

Code for Nova (based on Icehouse):
https://github.com/SnabbCo/nova/commits/nfv/icehouse

**Comment by thisisrmr** [comment]
Cool :-)

Is the bandwidth-aware host selection (Nova scheduling) also working as expected?

**Comment by lukego** [comment]
See [Neutron API Extensions](https://github.com/SnabbCo/snabb-nfv/wiki/Neutron-API-Extensions). Hosts are being selected with default Nova logic but then the specific 10G port on that host is chosen with bandwidth-awareness.

**Comment by thisisrmr** [comment]
Thanks for the link. Explains the current situation well.
