### ISSUE TITLE
intel_app fails to properly set vlan during reconfigure

### ISSUE THREAD

**Issue by eugeneia** [SnabbCo/snabbswitch#314]
While working on a patch that reconfigures the network in out `nfv/selftest.sh` (instead of starting new SnabbSwitch instances and VMs for every ports config) I noticed that the `intel_app` has a problem when its `vlan` parameter is reconfigured. E.g. it won't relay packets to the newly set vlan.

The behavior can be reproduced in this branch:

https://github.com/eugeneia/snabbswitch/tree/lib/nfv/selftest-keep-nfv

**Comment by lukego** [comment]
This should be fixed by #373.
