### ISSUE TITLE
Example on how to get going

### ISSUE THREAD

**Issue by plajjan** [SnabbCo/snabbswitch#330]
When I first started up snabb I had no idea how to put together a "configuration file". I read the README file in src/ and while it does document how to link apps together and so forth it doesn't provide a complete example. I found src/designs/loadgen/loadgen which I think is about the closest to a working example in the source tree.

My next conundrum was over the naming of the input and output interface of each app. It was less than obvious that Intel10G used rx/tx while many other applications use input/output.

I'd like to write a very short introduction to help other folks out there. A start:
https://github.com/SnabbCo/snabbswitch/wiki/Writing-an-application-configuration

hit or shit?

**Comment by lukego** [comment]
This is very good!

(Did I really miss that you opened this a month ago? Sorry!)
