### ISSUE TITLE
sysctl required for 1GB hugepages (bad error message)

### ISSUE THREAD

**Issue by lukego** [SnabbCo/snabbswitch#366]
Snabb Switch allocates HugeTLB pages with shared memory system calls. This will fail if the maximum allowed shared memory mapping size is smaller than the HugeTLB page size, which may be the default scenario if your kernel is configured with 1GB huge pages.

The symptom of this problem is that Snabb Switch fails to allocate a HugeTLB page (`shmget(2)` returns `-EINVAL`) and prints this message:

    Failed to allocate a huge page for DMA

and the solution is to increase the shared memory mapping limit with this command:

    sudo sysctl -w kernel.shmmax=1073741824

This is listed as a bug because Snabb Switch should print a more helpful error message.

**Comment by n-nikolaev** [comment]
The current value of `kernel.shmmax` can be read from here `/proc/sys/kernel/shmmax` and then compared to the huge page size.

**Comment by jeffbrl** [comment]
I'd like to give this one a shot. I will make a proposal in this issue's comments before writing the code.

**Comment by jeffbrl** [comment]
Use this logic after receiving `-EINVAL` from `shmget`.

If `sysinfo`'s `totalmem` struct member < 256 MB:

"Cannot allocate 128 MB of shared memory for snabbswitch. System memory is too low."

else:

"Cannot allocate 128 MB of shared memory for snabbswitch. Increase shared memory using 'sudo sysctl -w kernel.shmmax=1073741824'. Use the '-p' flag or edit sysctl.conf for persistence across reboots."

**Comment by lukego** [comment]
Here is another idea:

We could automatically increase the kernel `shmmax` setting and print a message to say that we are doing so. (Kind of like the way we automatically provision new huge pages.) If we are worried about users disliking this then we could add a `--no-change-kernel-settings` argument to print an error in these cases instead of automatically correcting them.

I note that on Ubuntu 15.04 the limit seems to be increased to essentially infinity:

```
$ sudo sysctl -a | grep shmmax
kernel.shmmax = 18446744073692774399
```
