### ISSUE TITLE
[neutron2snabb] 'vif_details.zone_gbps' translates to nfvconfig's 'gbps' which is never used

### ISSUE THREAD

**Issue by eugeneia** [SnabbCo/snabbswitch#408]
In `program/snabbnfv/neutron2snabb/neutron2snabb.lua`: `vif_details.zone_gbps` translates to nfvconfig `gbps` which is never used.

**Comment by eugeneia** [comment]
Should `zone_gbps` maybe be an upper limit to `rx_police_gbps` and `rx_police_gbps`?

**Comment by eugeneia** [comment]
@lukego Assinged you just for pinging purposes.

**Comment by lukego** [comment]
`zone_gbps` is not needed by the traffic process in the current implementation.
