### ISSUE TITLE
snabbnfv traffic default settings should not print so much debug info

### ISSUE THREAD

**Issue by lukego** [SnabbCo/snabbswitch#538]
The `snabbnfv traffic` program should default to not printing the link report or the app report (only the load report). Printing these reports has nontrivial overhead and should only be used for debugging.

The real solution to get detailed visibility without overhead will be SnabbTop (#472).

**Comment by lukego** [comment]
@eugeneia Could I tempt you to take a look at this one and the related #537 and #535?

**Comment by eugeneia** [comment]
@lukego Yup, on it!
