### ISSUE TITLE
Nix and NixOS

### ISSUE THREAD

**Issue by lukego** [SnabbCo/snabbswitch#578]
Recently @andywingo told me about the [Nix](http://nixos.org/nix/) package manager and [NixOS Linux](http://nixos.org/) distribution. I am wondering whether this could be a useful tool for Snabb Switch hackers. In particular I wonder if we could use it to improve the way we managed the lab servers and test  infrastructure.

The basic selling point of Nix is that it creates reproducible binaries. That is, you can tell it exactly the dependencies you want (compilers, libraries, build tools, etc) and you can refer to this permanently via a unique ID. So it solves a couple of problems: getting reproducible environments and using multiple environments independently.

Here are a few ideas for how we could use it:

1. Automatically setup lab servers according to known configurations e.g. of kernel, IOMMU settings, hugepage allocations, etc.
2. Have the CI run tests with multiple well-defined toolchains (e.g. QEMU version, VM image, GCC version, libc version, shellutils version, binutils version, etc).
3. Make easy-to-deploy Snabb network appliances e.g. automatically setup a Supermicro server to act as a firewall including serial port, lights-out manager, etc, configurations.

You can see it stimulates my imagination at least :-). I see this as potentially all the upsides of containers (mostly quick and reproducible builds/deployments) without the downsides (fighting with a restrictive sandbox that probably wants to block us from setting up IOMMU, accessing PCI devices, etc).

Thoughts?

**Comment by eugeneia** [comment]
Closing because I think this is superseded by #680 (except point 3 I guess, open a separate issue when required?)
