### ISSUE TITLE
snabbnfv traffic: warn when config file does not exist

### ISSUE THREAD

**Issue by lukego** [SnabbCo/snabbswitch#579]
`snabbnfv traffic` should print a warning when the configuration file does not exist. This will help users detect when they use the wrong filename by accident.

(This should be a warning and not an error because the behavior is to poll until the configuration file is created. The OpenStack setup allows the traffic process to start before its configuration is defined.)

**Comment by eugeneia** [comment]
I can look into this if you like. Just let me know so we don't end up duplicating effort again. ;)

**Comment by eugeneia** [comment]
Fixed in #679.
