### ISSUE TITLE
Recreate SnabbCo/luajit

### ISSUE THREAD

**Issue by lukego** [SnabbCo/snabbswitch#600]
I would like to recreate the SnabbCo/luajit Github repository.

The reason is boring Github logistics: now that LuaJIT has officially joined Github at http://github.com/LuaJIT/LuaJIT I would like to be able to send Pull Requests there from our fork (and sub-forks thereof) but I am told by Github support that this is not possible unless we recreate the repos.

Is it okay with everybody if I recreate SnabbCo/luajit? If you happen to have forked that repo then I believe you would need to do the same before you can send PRs.

I expect that the Git history itself will be preserved just fine. The Github-specific state is what will be lost e.g. the Issues and PRs on my lukego/luajit fork. C'est la vie...

More details @ LuaJIT/LuaJIT#50.

**Comment by eugeneia** [comment]
Closing because this issue is old and should be resolved by now.
